config/routes.rb
Cd2Cms::Engine.routes.draw do

  resources :projects do
    collection { post :sort }
  end

end

Rails.application.routes.draw do
get '/blog/history-of-property-market-in-norfolk-from-recession-ripple-effect-to-bouncing-back', to: redirect('/blogs/history-of-property-market-in-norfolk-from-recession-ripple-effect-to-bouncing-back', status: 301)
get '/blog/how-inflation-can-affect-property-investment-a-7-point-guide', to: redirect('/blogs/how-inflation-can-affect-property-investment-a-7-point-guide', status: 301)
get '/blog/sdlt-multiple-dwelling-relief-loophole-explained', to: redirect('/blogs/sdlt-multiple-dwelling-relief-loophole-explained', status: 301)
get '/blog/setting-and-reaching-goals-when-investing', to: redirect('/blogs/setting-and-reaching-goals-when-investing', status: 301)
get '/blog/norfolk-the-perfect-property-investment-place', to: redirect('/blogs/norfolk-the-perfect-property-investment-place', status: 301)
get '/blog/6', to: redirect('/blogs/6', status: 301)
get '/blog/islands-in-the-stream-that-is-what-we-are', to: redirect('/blogs/islands-in-the-stream-that-is-what-we-are', status: 301)
get '/blog/how-to-get-your-estate-agent-working-for-you-and-your-investment', to: redirect('/blogs/how-to-get-your-estate-agent-working-for-you-and-your-investment', status: 301)
get '/blog/one-of-the-hottest-property-markets-in-the-uk', to: redirect('/blogs/one-of-the-hottest-property-markets-in-the-uk', status: 301)
get '/blog/lunch-on-the-rooftop', to: redirect('/blogs/lunch-on-the-rooftop', status: 301)
get '/blog/1', to: redirect('/blogs/1', status: 301)
  get '/blog/', to: redirect('/blogs', status: 301)

  get '/Team', to: redirect('/about-us', status: 301)
  get '/about', to: redirect('/about-us', status: 301)

  mount Cd2Cms::Engine => '/admin'

  scope module: :cd2_cms do
    get '/sitemap', defaults: { :format => :xml }, to: 'sitemap#show'
  end

  resources :enquiries, only: [:new, :create], path: 'contact', path_names: {new: '/'} do
    get 'thanks', on: :collection
  end
  resources :blogs, only: [:index, :show]
  resources :projects, only: [:index, :show]

  resources :pages, only: :show, path: ''
  root 'pages#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Cd2Cms::PagesHelper

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @page = Cd2Cms::Page.get_from_url('blogs')
    @page_info = @page.page_info
  end

  def show
    @blog = Cd2Cms::Blog.get_from_url(params[:id])
  end

end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry_page

  def new
    @enquiry = Cd2Cms::Enquiry.new
  end

  def create
    @enquiry = Cd2Cms::Enquiry.new(enquiry_params)
    if @enquiry.save
      EnquiriesMailer.send_enquiry(@enquiry).deliver_now
      redirect_to thanks_enquiries_path
    else
      render :new
    end
  end

  def thanks
  end

  private

    def set_enquiry_page
      @page = Cd2Cms::Page.get_from_url('contact')
      @page_info = @page.page_info
    end

    def enquiry_params
      params.require(:enquiry).permit(:name, :email, :body, :phone, :project_id)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @page = Cd2Cms::Page.get_from_url(params[:id])
    @page_info = @page.page_info
    if @page_info.home_page && params[:id]
      redirect_to root_url, :status => 301
    else
      render @page.layout unless @page.layout.nil?
    end
    
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @page = Cd2Cms::Page.get_from_url('projects')
    @page_info = @page.page_info
    @projects = Cd2Cms::Project.includes(:page_info).where(cd2_cms_page_infos: {published: true})
  end

  def show
    @project = Cd2Cms::Project.get_from_url(params[:id])
    @page_info = @project.page_info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  include Cd2Cms::PagesHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/_admin_bar.html.haml
#on_site_admin_bar
  - if content_for?(:edit)
    .edit_link
      = yield :edit
  = render 'cd2_cms/application/content_menu'

  .right_link
    = link_to 'Log out', cd2_cms.destroy_user_session_path, method: :delete

app/views/application/_footer.html.haml
#subscribe_footer
  .tips_form_container
    %script{:charset => "utf-8", :src => "https://agilepropertypartners.activehosted.com/f/embed.php?id=1", :type => "text/javascript"}
    %script $(function(){$('#subscribe_footer').next('div').find('style').remove();});

#footer
  = image_tag("logo_icon.png")
  %p © Copyright 2016, Agile Property Partners.
  = link_to 'Terms and Conditions', '/terms-and-conditions'
  %p The Union Building - 51-59 Rose Lane - Norwich - Norfolk - NR1 1BY

app/views/application/_header.html.haml
#header
  #header_inner
    #logo
      = link_to image_tag('logo.png'), root_url

    #header_contact_info
      = link_to '01603 567804', "tel:01603567804"
      = mail_to 'info@a-pp.co.uk'
      = link_to image_tag('facebook.png'),'https://www.facebook.com/agilepropertypartners', class: 'social_link', target: 'blank'
      = link_to image_tag('linkedin.png'),'https://www.linkedin.com/company/10347283?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A10347283%2Cidx%3A2-2-3%2CtarId%3A1453477265610%2Ctas%3AAgile%20Property', class: 'social_link', target: 'blank'
      = link_to image_tag('twitter.png'),'https://twitter.com/agilepropertyp?lang=en-gb', class: 'social_link', target: 'blank'

    #menu_toggle
      .bar
      .bar
      .bar

    #main_nav
      -# Cd2Cms::Page.menu_pages.each do |page|
      =# link_to page.name, page, class: ('current' if request.path.include? page.to_param)

      <a href="/home">Home</a>
      <a href="/about-us">About Us</a>
      <a href="/investors">Investors</a>
      <a href="/norwich">Norwich</a>
      <a href="/projects">Projects</a>
      <a href="/careers">Careers</a>
      <a href="/blogs">Blog</a>
      <a href="/contact">Contact</a>

app/views/application/_home_enquiry_form.html.haml
= form_for(Cd2Cms::Enquiry.new) do |f|
  .field
    = f.label :name
    = f.text_field :name 
  .field
    = f.label :email
    = f.email_field :email

  .field
    = f.label :body, 'Your Message'
    = f.text_area :body
  .action
    = f.submit 'Send Enquiry'

app/views/application/_page_calls.html.haml
.sidebar_section
  %h3 Looking for Property investment in Norwich?
  %p If you would like to find out more, or have a question for us, we are happy to help.
  = link_to 'Get in touch', new_enquiry_path, class: 'sidebar_action'
  = link_to 'Call 01603 567804', 'tel:01603567804', class: 'sidebar_action'

app/views/application/_seo.html.haml
- provide :title, object.title
- provide :meta, object.meta_description

app/views/blogs/index.html.haml
- provide :image, @page.images&.first&.image&.url
= render 'seo', object: @page

.inner_content
  #page_banner
    = image_tag @page.feature_image&.short_banner

  .split_page
    .main_column.blogs_index

      .body_text
        .blogs_previews
          - Cd2Cms::Blog.order(created_at: :desc).first(10).each do |blog|
            .blog_preview
              %h2= blog.name
              .blog_preview_image
                = image_tag blog.feature_image.short_banner if blog.feature_image
              .blog_preview_text

                %p= truncate(strip_tags(blog.body), length: 250)
                = link_to 'More', "/blogs/#{blog.url_alias}"
    .side_column
      .sidebar_section
        %h3 Recent Blogs
        %ul
          - Cd2Cms::Blog.order(created_at: :desc).first(10).each do |blog|
            %li= link_to blog.name, "/blogs/#{blog.url_alias}"

app/views/blogs/show.html.haml
- provide :image, @blog.feature_image&.url
.inner_content
  #page_banner
    = image_tag @blog.feature_image&.slideshow if @blog.feature_image

  .split_page
    .main_column
      .body_text
        %h1= @blog.name
        = social_share_button_tag(@blog.title)
        = raw @blog.body
    .side_column
      = render 'page_calls'
      .gallery_sidebar
        - @blog.images.where(featured_image: false).each do |image|
          .gallery_image
            = image_tag image.image

app/views/cd2_cms/application/_content_menu.html.haml
= link_to 'Pages', cd2_cms.pages_path
= link_to 'Projects', cd2_cms.projects_path
= link_to 'Blogs', cd2_cms.blogs_path

app/views/cd2_cms/application/_imageable_fields.html.haml
= f.fields_for :images do |f|
  .fields_for.columns{class: ('not_persisted' if f.object.image_cache.present?)}
    = f.hidden_field :image_cache
    = f.hidden_field :order, class: 'order_field'
    .sort_handle= fa_icon('ellipsis-v')
    .column.column--2
      .image_preview
        = image_tag f.object.image.preview
    .column.column--2
      .field
        = f.label :alt
        = f.text_field :alt
      .field
        = f.label :caption
        = f.text_field :caption
      - if @object.try(:image_text)
        .field
          = f.label :body
          = f.text_area :body, class: 'wysiwyg'
      - if @object.try(:image_slideshow)
        .field
          = f.label :slideshow_image
          = f.check_box :slideshow_image

      .field
        = f.label :featured_image
        = f.check_box :featured_image
      .field
        = f.label :_destroy, 'Delete Image?'
        = f.check_box :_destroy, class: '_destroy'

= f.label :new_images
= f.file_field :new_images, multiple: true, data: {auto_submit: :upload}
= button_tag 'Upload', name: :commit, value: :upload

app/views/cd2_cms/pages/_admin_fields.html.haml
.field
  = f.label :layout
  = f.text_field :layout

= f.fields_for :page_info do |ff|
  .field
    = ff.label :home_page
    = ff.check_box :home_page

.field
  = f.label :image_text
  = f.check_box :image_text

.field
  = f.label :image_slideshow
  = f.check_box :image_slideshow

app/views/cd2_cms/pages/_extra_fields.html.haml
- if @object.home_page?
  .field
    = f.label :video_url, 'Video Embed Code'
    = f.text_field :video_url

app/views/cd2_cms/projects/_form.html.haml
#form_page
  = form_for @object do |f|
    #upper_form
      .title_field
        = f.text_field :name, placeholder: 'Project name'
      .right_form_buttons
        = f.submit
        = link_to 'Delete', @object, method: :delete, data: { confirm: 'Are you sure? This cannot be undone' }, class: 'delete_button'

    #main_form

      .tabs_container

        = radio_button_tag :tab, :content, true
        - if @object.class.included_modules.include? Cd2Cms::SitePage
          = radio_button_tag :tab, :metadata, (params[:tab]=='metadata')
        - if @object.class.included_modules.include? Cd2Cms::Imageable
          = radio_button_tag :tab, :media, (params[:tab]=='media')
        = radio_button_tag :tab, :publish, (params[:tab]=='publish')

        .tab_headings
          = label_tag :tab_content, 'Content'
          - if @object.class.included_modules.include? Cd2Cms::SitePage
            = label_tag :tab_metadata, 'Meta Data'
          - if @object.class.included_modules.include? Cd2Cms::Imageable
            = label_tag :tab_media, 'Media'
          = label_tag :tab_publish, 'Publish'

        .form_tabs
          .form_tab.tab--content_tab
            .field
              = f.label :body
              = f.text_area :body, class: 'wysiwyg'
            .field
              = f.label :keypoints
              = f.text_area :keypoints, class: 'wysiwyg'
            .field
              = f.label :google_map, 'Map Embed Code'
              = f.text_field :google_map
            //.field
            //  = f.label :status
            //  = f.select :status, Cd2Cms::Project.statuses.keys.map {|s| [s.titleize, s]}, selected: f.object.status, prompt: '-- status --'

          - if @object.class.included_modules.include? Cd2Cms::SitePage
            .form_tab.tab--metadata_tab
              = render 'page_info_fields', f: f

          - if @object.class.included_modules.include? Cd2Cms::Imageable
            .form_tab.tab--media_tab.reorderable
              = render 'imageable_fields', f: f

          .form_tab.tab--publish_tab
            .field
              = f.label :published
              = f.check_box :published


    #lower_form
      .right_form_buttons
        = f.submit
        = link_to 'Delete', @object, method: :delete, data: { confirm: 'Are you sure? This cannot be undone' }, class: 'delete_button'

app/views/cd2_cms/projects/_index_head.html.haml
%th.prime_column= sort_link(@q, :name)
%th= sort_link(@q, :created_at)
%th= sort_link(@q, :published)
%th= sort_link(@q, :status)
%th.icon_column Edit
%th.icon_column Delete

app/views/cd2_cms/projects/_index_row.html.haml
%tr{id: "project_#{object.id}"}
  %td.sort_handle= fa_icon('ellipsis-v')
  %td= object.name
  %td= object.created_at.strftime('%D')
  %td= object.published ? 'Yes' : 'No'
  %td= object.status&.titleize
  %td= link_to fa_icon('edit'), [:edit, object], class: 'table_icon'
  %td= link_to fa_icon('trash'), object, method: :delete, data: { confirm: 'Are you sure you wish to delete?' }, class: 'table_icon delete_icon'

app/views/enquiries/new.html.haml
= render 'seo', object: @page

.inner_content

#contact_panel
  = raw @page.body
  = form_for(@enquiry) do |f|
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :email
      = f.email_field :email
    .field
      = f.label :phone
      = f.text_field :phone
    - if params[:project_id]
      .field
        = f.label :project_id
        = f.collection_select :project_id, Cd2Cms::Project.all, :id, :name, selected: params[:project_id]
    .field
      = f.label :body, 'Your Message'
      = f.text_area :body
    .action
      = f.submit 'Send Enquiry'
  .contact_deets
    .contact.phone_contact
      %span Phone
      %span 01603 567804
    .contact.email_contact
      %span Email
      %span info@a-pp.co.uk
    .contact.contact_address
      Agile Property Partners - The Union Building - 51-59 Rose Lane - Norwich - Norfolk - NR1 1BY

app/views/enquiries/thanks.html.haml
= render 'seo', object: @page

.inner_content
  #page_banner
    = image_tag @page.feature_image&.slideshow rescue ''

  .split_page
    .main_column
      .body_text
        %h1 Thank you for getting in touch
        %p Somebody from the team will take a look and get back to you. #{link_to 'Back to Home', root_path}

app/views/layouts/application.html.haml
!!!
%html{:prefix => "og: http://ogp.me/ns#"}
  %head
    = meta_tags
    - if content_for? :image
      %meta{:content => yield(:image), :property => "og:image"}/
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:content => "initial-scale=1", :name => "viewport"}
    %link{:href => "/fav.png", :rel => "shortcut icon", :type => "image/png"}/
    %script{:src => "https://use.typekit.net/idx4cdr.js"}
    :javascript
      try{Typekit.load({ async: true });}catch(e){}
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-74436887-1', 'auto');
      ga('send', 'pageview');
    :javascript
      var trackcmp_email = '';
      var trackcmp = document.createElement("script");
      trackcmp.async = true;
      trackcmp.type = 'text/javascript';
      trackcmp.src = '//trackcmp.net/visit?actid=999794128&e='+encodeURIComponent(trackcmp_email)+'&r='+encodeURIComponent(document.referrer)+'&u='+encodeURIComponent(window.location.href);
      var trackcmp_s = document.getElementsByTagName("script");
      if (trackcmp_s.length) {
      trackcmp_s[0].parentNode.appendChild(trackcmp);
      } else {
      var trackcmp_h = document.getElementsByTagName("head");
      trackcmp_h.length && trackcmp_h[0].appendChild(trackcmp);
      }
    / Facebook Pixel Code
    :javascript
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n; n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0; t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, document,'script','https://connect.facebook.net/en_US/fbevents.js'); fbq('init', '1472243636438504'); fbq('track', "PageView");
    %noscript
      %img{:height => "1", :src => "https://www.facebook.com/tr?id=1472243636438504&ev=PageView&noscript=1", :style => "display:none", :width => "1"}/

  %body
    - if signed_in?
      = render 'admin_bar'

    = render 'header'
    = yield
    = render 'footer'

app/views/pages/about.html.haml
- provide :image, @page.feature_image&.url
= render 'seo', object: @page

.inner_content
  = image_tag @page.feature_image

  .split_page
    .main_column
      .body_text
        %h1= @page.name
        = raw @page.body
    .side_column
      
      .meet_the_team.sidebar_section
        - @page.images.where(featured_image: false).each do |team_member|
          = image_tag team_member.image.team
          %h4= team_member.caption
          = raw team_member.body
      = render 'page_calls'

app/views/pages/home.html.haml
- provide :image, @page.images&.first&.image&.url
= render 'seo', object: @page

#banner_image
  #page_banner.flexslider
    %ul.slides
      - @page.images.each do |image|
        %li{style: "background-image: url(#{image.image.home_slideshow})"}
          .slide_banner_text
            .banner_overlay_text
              = raw image.body



#intro_panel.home_intro
  .inner_content
    %h2 We make property investing in Norfolk <span class="emphasis">easy</span>
    %h3 Agile Property Partners is a Norwich based company that&nbsp;excels in finding successful investment opportunities – providing a lucrative and safe ROI for our partners.
    .video= raw @page.video_url
    = raw @page.body

#home_project_previews
  %h2 Latest Projects
  .inner_content
    - Cd2Cms::Project.includes(:page_info).where(cd2_cms_page_infos: {published: true}).first(3).each do |project|
      .panel_preview
        - if project.feature_image
          .panel_image
            = image_tag project.feature_image&.team if project.feature_image
        .panel_text
          %h3= project.name
          %p= truncate(strip_tags(project.body), length: 100)
          = link_to 'More', project

#home_news_previews
  %h2 Latest News
  .inner_content
    - Cd2Cms::Blog.order(created_at: :desc).first(3).each do |blog|
      .panel_preview
        .panel_image
          = image_tag blog.feature_image&.team if blog.feature_image
        .panel_text
          %h3= blog.name
          %p= truncate(strip_tags(blog.body), length: 100)
          = link_to 'More', "/blogs/#{blog.url_alias}"

app/views/pages/show.html.haml
- provide :image, @page.feature_image&.url
= render 'seo', object: @page

.inner_content
  - if @page.feature_image
    #page_banner
      = image_tag @page.feature_image&.slideshow

  .split_page
    .main_column
      .body_text
        %h1= @page.name
        = raw @page.body
    .side_column
      = render 'page_calls'
      .gallery_sidebar
        - @page.images.where(featured_image: false).each do |image|
          .gallery_image
            = image_tag image.image

app/views/pages/slideshow.html.haml
- provide :image, @page.feature_image&.url
= render 'seo', object: @page

.inner_content
  #page_banner.flexslider
    %ul.slides.show_page_slides
      - @page.images.each do |image|
        %li
          = image_tag image.image.slideshow


  .split_page
    .main_column
      .body_text
        %h1= @page.name
        = raw @page.body
    .side_column
      = render 'page_calls'

app/views/projects/_project.html.haml
.project_preview{data: {status: (project.status || true)}}
  %h2= project.name
  .project_preview_image
    = image_tag(project.feature_image&.team || '')
  .project_preview_text
    = raw project.keypoints
    .project_actions
      = link_to 'More', project
      = link_to 'Make Enquiry', enquiries_path(project_id: project.id)
  //.project_status
  //  = project.status&.titleize

app/views/projects/index.html.haml
- provide :image, @page.feature_image&.url
= render 'seo', object: @page

.inner_content
  #page_banner
    = image_tag @page.feature_image&.slideshow

  .split_page
    .main_column
      .body_text
        %h1 Projects
        = raw @page.body
      //.filter_statuses
      //  = link_to 'All', '#', data: {filter: 'all'}, class: 'active'
      //  - Cd2Cms::Project.statuses.collect(&:first).each do |status|
      //    = link_to status.titleize, '#', data: { filter: status }
      .projects_previews
        = render partial: 'project', collection: @projects

    .side_column
      = render 'page_calls'

app/views/projects/show.html.haml
- provide :image, @project.feature_image&.url
.inner_content
  - if @project.feature_image
    = image_tag(@project.feature_image&.short_banner)
  .split_page
    .main_column
      .body_text
        %h1= @project.name
        = raw @project.body
        - if @project.keypoints.present?
          .keypoints
            = raw @project.keypoints
      .google_map
        = raw @project.google_map
    .side_column
      = render 'page_calls'
.project_images
  .project_images_inner
    - @project.images.each do |image|
      .project_image= link_to image_tag(image.image.team), image.image.url, data: {lightbox: 'project_images'}